# Checks new PRs for valid Addition or Task types labels
# Fails if none of these labels are included

name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "Task : Code, Task : Audio, Task : Exercises, Task : Composition, Addition : Documentation, Addition : Media, Addition : Examples, Addition : Exercises, Addition : Lecture, Addition : Material"
